name: Docker Image CI

on:
  push:
    branches: [ main, feature/Docker ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    env:
      tag: ${{ github.run_id }}

    runs-on: self-hosted

    steps:

    - uses: actions/checkout@v3
    - name: Run an echo
      run : echo "My Message"
    - name: Build the Docker image (now)
      run : docker build --tag ${{ secrets.JF_ARTIFACTORY_REGISTRY }}/aws-windows-docker-local/my-image-windows:${{ env.tag }} .
    - name: Run image
      run : docker run --rm ${{ secrets.JF_ARTIFACTORY_REGISTRY }}/aws-windows-docker-local/my-image-windows:${{ env.tag }}
      
    - name: Login to JFrog-Registry
      uses: docker/login-action@v1 
      with:
        registry: ${{ secrets.JF_ARTIFACTORY_REGISTRY }}
        username: ${{ secrets.JF_ARTIFACTORY_USER }}
        password: ${{ secrets.JF_ARTIFACTORY_PASSWORD }}
  
    - name: Push Docker-Image
      run: docker push ${{ secrets.JF_ARTIFACTORY_REGISTRY }}/aws-windows-docker-local/my-image-windows:${{ env.tag }}
    
    # Delete Docker-Image
    - name: Delete Docker-Image 
      run: |
        docker rmi ${{ secrets.JF_ARTIFACTORY_REGISTRY }}/aws-windows-docker-local/my-image-windows:${{ env.tag }}